### ISSUE TITLE
email the group notifying them of this repo?

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/gso#2]
@strubell : Should we send out a group email saying something like,

We're working on a constitution for the group and would appreciate your feedback! Attached is a copy of our current draft of the constituiton. If you have remarks, please open a github issue with the section number and your comments, and tag one of us (@etosch, @strubell) in the comment.

**Comment by strubell** [comment]
Yes, totally

**Comment by etosch** [comment]
We should set a goal for percent completed.

**Comment by etosch** [comment]
I put this under a later milestone, but maybe we want a different email sent out sooner -- let's tell people that if they want to participate in the writing, they should star this repository, and we'll add them as contributors. If you think this is a good way to go, can you send the email out today?

**Comment by strubell** [comment]
Yes I'll send it out this evening, basically I just still have to configure
my email to send as cs women cochairs, heh

**Comment by etosch** [comment]
YEah, I just changed my email client and need to do that too. :-/

**Comment by etosch** [comment]
I just sent it from women@cs, since I already had that account set up in 
my other mail client.

**Comment by strubell** [comment]
thanks

**Comment by etosch** [comment]
Closing this because the email was sent. No stars so far...
