### ISSUE TITLE
Do a pass over the positions and give feedback

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/gso#5]
@strubell  I just filled out the org positions. Could you take a look?

**Comment by strubell** [comment]
Awesome, thanks! Looks good overall. In general I'd be concerned about actually filling all these roles. 

Just a couple small things: what is Faculty Representative, afaik that's not a position we have right now, right? Similarly, what exactly is the role of the GWIS liason and why do we need one?

**Comment by etosch** [comment]
So right now I see these as being flexible roles, where some are 
required (e.g., cochairs) and some can be added when the group is 
larger. That way, hen the group is small and there isn't a ton going on, 
it can be scaled back, but when the group grows, there are predefined 
roles for more people to expand into. There are always very enthusiastic 
incoming students who are looking to get involved, so having some 
lower-commitment predefined roles available has the advantage of looping 
people, giving them something small to do, to get a sense of how things 
are run.

The faculty representative role was something we talked about last 
semester, and ran by Lori, who suggested we have the grad reps bring it 
up as a motion during a faculty meeting. The idea behind it was that 
there should be someone who knows the female student body well enough to 
be able to speak to those concerns.

The GWiS liaison is basically someone who can keep that line of 
communication open. Since GWiS already does a ton of programming for 
their membership, it wouldn't make sense for us to repeat that. It would 
make more sense to have a CS Women person who is involved in GWiS who 
can keep up with what's going on there and basically communicate between 
our group and theirs. Not everything they do will be relevant to our 
membership, but some of it certainly will. I met with them to discuss 
the logistics of running these skills workshops, since they had run the 
python ones. It would be great to keep up the flow of information 
between the two groups, and given the volume of emails we get as 
co-chairs, it would be really useful to have someone else around to 
manage those.

On 9/1/15 10:02 AM, Emma Strubell wrote:

> Awesome, thanks! Looks good overall. In general I'd be concerned about 
> actually filling all these roles.
> 
> Just a couple small things: what is Faculty Representative, afaik 
> that's not a position we have right now, right? Similarly, what 
> exactly is the role of the GWIS liason and why do we need one?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSWomenUMass/gso/issues/5#issuecomment-136732313.

## 

Emma Tosch
PhD Candidate, College of Information & Computer Sciences
University of Massachusetts Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch

**Comment by strubell** [comment]
Cool, sounds good. I think the faculty rep is great, and in general I am all for distributing the tasks (by having other people deal with various emails / opportunities available)
