### ISSUE TITLE
contact GSO dude

### ISSUE THREAD

**Issue by etosch** [CSWomenUMass/gso#8]
@strubell : I can't find the email that has the guy from GSS who originally emailed us (me?) about becoming a GSO. Do you happen to have his name/details?

**Comment by strubell** [comment]
Found it, Daniel Morales, who appears to be the GSS Treasurer, and whose email is: gss-treas@grad.umass.edu

**Comment by etosch** [comment]
thanks! I had a major mail search fail...

On 9/1/15 10:04 AM, Emma Strubell wrote:

> Found it, Daniel Morales, who appears to be the GSS Treasurer, and 
> whose email is: gss-treas@grad.umass.edu mailto:gss-treas@grad.umass.edu
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSWomenUMass/gso/issues/8#issuecomment-136732662.

## 

Emma Tosch
PhD Candidate, College of Information & Computer Sciences
University of Massachusetts Amherst
etosch@cs.umass.edu
http://cs.umass.edu/~etosch
